name: Run tests against PR (with HPOS)
on:
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions: {}

env:
    PR_NUMBER: ${{ github.event.pull_request.number }}
    PR_TITLE: ${{ github.event.pull_request.title }}

jobs:
    hpos-api-tests-run:
        name: Runs API tests (HPOS enabled)
        if: github.event.pull_request.user.login != 'github-actions[bot]'
        runs-on: ubuntu-20.04
        permissions:
            contents: read
        env:
            ALLURE_REPORT_DIR: ${{ github.workspace }}/plugins/woocommerce/tests/api-core-tests/api-test-report/allure-report
            ALLURE_RESULTS_DIR: ${{ github.workspace }}/plugins/woocommerce/tests/api-core-tests/api-test-report/allure-results
            ENABLE_HPOS: 1
        steps:
            - uses: actions/checkout@v3

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo
              with:
                  build-filters: woocommerce

            - name: Setup local test environment
              uses: ./.github/actions/tests/setup-local-test-environment
              with:
                  test-type: api

            - name: Run API tests
              id: api-action
              uses: ./.github/actions/tests/run-api-tests
              with:
                  artifact-name: API Test report (HPOS enabled)
                  report-title: API Test report (HPOS enabled) for "${{ env.PR_TITLE }} (#${{ env.PR_NUMBER }})"
                  tests: hello # mytodo remove

            - name: Publish report
              if: success() || ( failure() && steps.api-action.result == 'failure' )
              uses: ./.github/actions/tests/reports/publish-report-pr
              with:
                  key-id: ${{ secrets.REPORTS_AWS_ACCESS_KEY_ID }}
                  region: ${{ secrets.REPORTS_AWS_REGION }}
                  access-key: ${{ secrets.REPORTS_AWS_SECRET_ACCESS_KEY }}
                  reports-home: ${{ secrets.REPORTS_BUCKET }}
                  feat-slug: hpos
                  test-type: api

    hpos-e2e-tests-run:
        name: Runs E2E tests (HPOS enabled)
        needs: [hpos-api-tests-run]
        runs-on: ubuntu-20.04
        permissions:
            contents: read
        env:
            ALLURE_REPORT_DIR: ${{ github.workspace }}/plugins/woocommerce/tests/e2e-pw/test-results/allure-report
            ALLURE_RESULTS_DIR: ${{ github.workspace }}/plugins/woocommerce/tests/e2e-pw/test-results/allure-results
            ENABLE_HPOS: 1
        steps:
            - uses: actions/checkout@v3

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo
              with:
                  build-filters: woocommerce

            - name: Setup local test environment
              uses: ./.github/actions/tests/setup-local-test-environment
              with:
                  test-type: e2e

            - name: Run E2E tests
              id: e2e-action
              timeout-minutes: 60
              uses: ./.github/actions/tests/run-e2e-tests
              env:
                  E2E_MAX_FAILURES: 15
              with:
                  artifact-name: E2E Test report (HPOS enabled)
                  report-title: E2E Test report (HPOS enabled) for "${{ env.PR_TITLE }} (#${{ env.PR_NUMBER }})"
                  tests: basic.spec.js # mytodo remove

            - name: Publish report
              if: success() || ( failure() && steps.e2e-action.result == 'failure' )
              uses: ./.github/actions/tests/reports/publish-report-pr
              with:
                  key-id: ${{ secrets.REPORTS_AWS_ACCESS_KEY_ID }}
                  region: ${{ secrets.REPORTS_AWS_REGION }}
                  access-key: ${{ secrets.REPORTS_AWS_SECRET_ACCESS_KEY }}
                  reports-home: ${{ secrets.REPORTS_BUCKET }}
                  feat-slug: hpos
                  test-type: e2e
